name: Build, Analyze and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Télécharger le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t trabelsihammamimanel/php-web-app:latest .

      # Étape 4 : Pousser l'image Docker
      - name: Push Docker image
        run: |
  docker push trabelsihammamimanel/php-web-app:latest

      # Étape 5 : Connexion à Azure et déploiement
      - name: Log in to Azure and Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: MohsenManelWebApp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: trabelsihammamimanel/php-web-app:latest
